### ISSUE TITLE
[UI] Cannot create a namespaced resource when there are no namespaces

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempting to create an app, config, service etc is not possible if a workspace does not exist.
The user gets a blank page with an unhandled error:
![image](https://user-images.githubusercontent.com/37271841/174282492-fe0bd2b9-73fa-4043-a0ec-7a2401ebc794.png)

This issue partially affects: https://github.com/epinio/epinio-end-to-end-tests/issues/180

### Expected Behavior

The user should be able to create any resource even if a namespace does not exist by allowing it to create the namespace directly from the resource option selected:
![image](https://user-images.githubusercontent.com/37271841/174282829-d3b5ffb8-5176-461a-8dad-ee481410d19c.png)

### Steps To Reproduce

1. install latest epinio standalone ui using [install-latest-standalone-iu-md](https://github.com/epinio/ui/blob/dev/docs/developer/install-latest-standalone-ui.md) 
2. Without any namespace created attempt to create a configuration

### Environment

```markdown
- OS:Linux
- Architecture:amd64
- Epinio Version:Epinio Version: v0.9.0
- Cluster:
  - Provider:k3d
  - Options:
  - Kubernetes Version:
```

### Logs

```markdown
fetch.client.js:75 Error in fetch(): TypeError: Cannot read properties of undefined (reading 'meta')
    at _callee$ (services.vue:54:1)
    at tryCatch (runtime.js:45:1)
    at Generator.invoke [as _invoke] (runtime.js:274:1)
    at prototype.<computed> [as next] (runtime.js:97:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
```
```


### Anything else?

_No response_

**Comment by mmartin24** [comment]
Note:
While testing this ticket on epinio-dev, I noticed an ugly crash if you attempt to create a Namespace without clicking first in the "Create a new Namespace" option
[crashEnteringNamespaceAndEnter.zip](https://github.com/epinio/ui/files/8927615/crashEnteringNamespaceAndEnter.zip)

![image](https://user-images.githubusercontent.com/37271841/174302986-e847b40f-ef4f-4005-bf3b-47ef9618f2e5.png)
![image](https://user-images.githubusercontent.com/37271841/174302950-98ff6340-acc8-4025-b731-c3e68b7d332a.png)
While this is only dev, we should ensure it does not happen on main later

**Comment by mmartin24** [comment]
Verified fix in epinio-dev
[okCreateNamespaceEnter.zip](https://github.com/epinio/ui/files/8928415/okCreateNamespaceEnter.zip)
