### ISSUE TITLE
[UI] Create Configuration broken in epinio-dev

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to create a configuration in `epinio-dev` the page an overlay appears with "Loading" and creation is not possible.
Note: at the moment of this ticket this occurs at this point in git history:

```
9353146d9 (HEAD -> epinio-dev, origin/epinio-dev) Merge pull request #7299 from richard-cox/dex-pr
``` 

Screenshot:
![image](https://user-images.githubusercontent.com/37271841/218523200-b5bb7191-4600-4419-800e-4cce02cd01ce.png)

Video:
https://user-images.githubusercontent.com/37271841/218523219-b9916d11-dd3f-4fce-b52b-5d1593849c39.mov

### Expected Behavior

Create configuration should be possible

### Steps To Reproduce

1. Install latest Epinio version (currently in v1.6.2-33-gdd8c7020) using k3d
2. Patch latest UI image:
```
kubectl set image -n epinio deployment/epinio-ui epinio-ui=ghcr.io/epinio/epinio-ui:latest-next
```
3. Log in as admin and try to create a configuration

### Environment

```markdown
- OS: Linux
- Architecture: amd64
- Epinio Version: v1.6.2-33-gdd8c7020
- Cluster:
  - Provider: K3d
  - Options:
  - Kubernetes Version: v1.25.4+k3s1
-Epinio
```

### Logs

```markdown
Javascript error:


console.js:31 TypeError: Cannot read properties of undefined (reading 'match')
    at y.get (configurations.js:49:22)
    at f.<anonymous> (configurations.vue?1c23:1:503)
    at t._render (vue.runtime.esm.js:3569:22)
    at f.r (vue.runtime.esm.js:4081:21)
    at Tn.get (vue.runtime.esm.js:4495:25)
    at Tn.run (vue.runtime.esm.js:4570:22)
    at An (vue.runtime.esm.js:4326:13)
    at Array.<anonymous> (vue.runtime.esm.js:1989:12)
    at ce (vue.runtime.esm.js:1915:12)
```

**Comment by mmartin24** [comment]
I saw this item was moved to review. 
I checked it worked on the fixed branch ([link](https://github.com/rancher/dashboard/pull/8157#issuecomment-1428378549)) but this is still currently happening on `epinio-dev` so I think is safer to keep it open here until the fix reaches the main branch.  
@scures, could you please ping me when    **https://github.com/rancher/dashboard/pull/8157** is merged?  (or I can simply check once the fix is in directly). Thanks.

**Comment by mmartin24** [comment]
thanks @scures. Checked and working on latest epinio-dev:

![image](https://user-images.githubusercontent.com/37271841/218747903-afc38624-47e1-447d-82aa-11ea19595108.png)
