### ISSUE TITLE
[UI] Uncaught error after an app is pushed and clicking in Done

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After pushing an application in UI anc clicking Done, an uncaught error appears on dev tools

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'normalize')
    at applications.vue:116:47
    at v (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at l (asyncToGenerator.js:25:9)
(
```

https://user-images.githubusercontent.com/37271841/232078644-14a00639-3273-422a-ac18-8d2f1e98b2a5.mov

### Expected Behavior

The error should be handled.

### Steps To Reproduce

1. Install latest Epino and `epinio-dev` UI
2. Push an app (ie this one using source type = file [sample-app.tar.gz](https://github.com/epinio/ui/files/11234144/sample-app.tar.gz) 
3. Wait until is loaded
4. With chrome dev tools opened, click on "Done"

### Environment

```markdown
- OS: Linux
- Architecture: amd64
- Epinio Version:  v1.7.1-28-gf8057ed9 & latest epinio-dev for ui
- Cluster:
  - Provider:k3d
  - Options: 1 node
  - Kubernetes Version: v1.25.4+k3s1
```

**Comment by mmartin24** [comment]
This issue seems solved in latest epinio-dev.
Closing issue
